= 终端下的默认Emacs快捷键命令使用

默认的Ｂash绑定的是Emacs的快捷键，可以修改成Vi(set - o vi)的操作方式。

启动编辑器
Ctrl+x-Ctrl+x打开一个编辑器

	根据 $FCEDIT 或 $EDITOR 环境变量打开对应的编辑器,若这两个变量都为空，则运行emacs
控制屏幕
	• Ctrl+l清屏（同clear命令）
	• Ctrl+s暂停屏幕输出
	• Ctrl+q恢复Ctrl+s后的屏幕输出
命令行光标
	• Ctrl+a/Home移动光标到行首
	• Ctrl+e/End移动光标到行尾
	• Ctrl+b/左箭头<-向左移动一个字符
	• Ctrl+f/右箭头->向右移动一个字符
	• Ctrl+左箭头<-/Alt+b/ESC-b向左移动一个单词（以空格分隔)
	• Ctrl+右箭头->/Alt+c/ESC-f向右移动一个单词（以空格分隔)
	Alt+c向右移动一个单词时会将单词首字母变大写
搜索历史
	• 上箭头/下箭头上箭头搜索上一条历史，下箭头相反
	• Ctrl+p/Ctp+n同上下箭头
	• Ctrl+r搜索匹配的历史关键字
	• Ctrl+s反向搜索
	• Ctrl+g取消反向搜索
命令行删除文本
	• Ctrl+d/Delete 删除光标所在的字符
	• Ctrl+k 删除光标到行尾的的文本
	• Ctrl+x-Backspace 删除光标到行首的文本
命令行修改文本
	• Ctrl+t 光标处字符和前一个字符交换位置
	• ESC+t与光标前一各单词交换位置（以空格分隔）
	• ESC+u 将光标所在处单词字符到词尾转大写
	• ESC+l 将光标所在单词字符到词尾写
	• Esc+c 将光标所在单词字符转大写，单词光标后字符到词尾转小写
控制进程
	• Ctrl+z 挂起当前进程
	• Ctrl+c 结束当前进程
	• Ctrl+d 退出Bash（同exit命令）
Bang(!)命令
	• !! 执行上一条命令
	• !top 执行最近以top开头的命令
	• !top:p 只显示但不执行最近以top开头的命令
	• !$ 将上个命令中最后一个单词作为新命令执行（同Alt+.但要回车执行)
	• !$:p 显示!$要执行的命令
	• !* 执行上个命令中首单词除外的命令
	• !*:p 显示!*要执行的命令
更多命令
查看帮助手册
（完）
